name = "GeoRequestSimulator"
uuid = "aebb6fd8-4066-410e-987c-a34f476c5ce8"
authors = ["Cheikh Ahmed"]
version = "1.0.0-DEV"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
